/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author karthikap733
 */
    import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class CurrentAccount extends javax.swing.JFrame 
{
     /**
    *
    */
    private static final long serialVersionUID = 1L;
    int id = 1;
     FileWriter fw;
     BufferedWriter bw;
     Login1 obj=null;
     public CurrentAccount()
     {
         initComponents();
     }
    public CurrentAccount(Login1 obj) throws IOException{
        this.obj=obj;
        initComponents();
//        File f=new File("CSV"+id+".txt");
//        fw=new FileWriter(f,false);
//        bw=new BufferedWriter(fw);  
//        bw.write(0);
    }

    /** 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 =new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        close = new javax.swing.JButton();
        debit = new javax.swing.JButton();
        request = new javax.swing.JButton();
        benef = new javax.swing.JButton();
        add = new javax.swing.JButton();
        balance = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0,0,0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");
        jPanel1.setName(""); // NOI18N

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255,255,255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Current Account");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 90);

        jPanel2.setBackground(new java.awt.Color(255,255,255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setDoubleBuffered(false);

        close.setBackground(new java.awt.Color(0,0,0));
        close.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        close.setForeground(new java.awt.Color(255,255,255));
        close.setText("Close Account");
        close.setToolTipText("");
        close.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        close.setBorderPainted(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        debit.setBackground(new java.awt.Color(0,0,0));
        debit.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        debit.setForeground(new java.awt.Color(255,255,255));
        debit.setText("Debit Money");
        debit.setToolTipText("");
        debit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        debit.setBorderPainted(false);
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });

        request.setBackground(new java.awt.Color(0,0,0));
        request.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        request.setForeground(new java.awt.Color(255,255,255));
        request.setText("Request");
        request.setToolTipText("");
        request.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        request.setBorderPainted(false);
        request.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestActionPerformed(evt);
            }
        });

        benef.setBackground(new java.awt.Color(0,0,0));
        benef.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        benef.setForeground(new java.awt.Color(255,255,255));
        benef.setText("Add beneficiary");
        benef.setToolTipText("");
        benef.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        benef.setBorderPainted(false);
        benef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                benefActionPerformed(evt);
            }
        });

        add.setBackground(new java.awt.Color(0,0,0));
        add.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        add.setForeground(new java.awt.Color(255,255,255));
        add.setText("Add Money");
        add.setToolTipText("");
        add.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        add.setBorderPainted(false);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        balance.setBackground(new java.awt.Color(0,0,0));
        balance.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        balance.setForeground(new java.awt.Color(255,255,255));
        balance.setText("Balance Enquiry");
        balance.setToolTipText("");
        balance.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        balance.setBorderPainted(false);
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(0,0,0));
        exit.setFont(new java.awt.Font("Courier New", 3, 30)); // NOI18N
        exit.setForeground(new java.awt.Color(255,255,255));
        exit.setText("Exit");
        exit.setToolTipText("");
        exit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 0, true));
        exit.setBorderPainted(false);
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(debit, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                    .addComponent(request, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(benef))
                .addGap(43, 43, 43))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(benef, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(debit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(close, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(request, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 90, 640, 520);

        pack();
    }// </editor-fold>                        

                                     

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {                                      
      closeAccount close=new closeAccount(obj);
      close.setVisible(true);
    }                                     

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {                                      
        Withdraw  with=new Withdraw(obj);
        with.setVisible(true);
    }                                     

    private void requestActionPerformed(java.awt.event.ActionEvent evt) {                                        
        request req=new request(obj);
        req.setVisible(true);
    }                                       

    private void benefActionPerformed(java.awt.event.ActionEvent evt) {                                      
        AddBeneficiary_1 benef=new AddBeneficiary_1(obj);
        benef.setVisible(true);
    }                                     

    private void addActionPerformed(java.awt.event.ActionEvent evt) {                                    
    AddMoney a=new AddMoney(obj);
    a.setVisible(true);
    }                                   

private void balanceActionPerformed(java.awt.event.ActionEvent evt) {                                        
       Balance b=new Balance(obj);
       b.setVisible(true);
    }                                       

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {                                     
      System.exit(0);
    }                                    

   
    public static void main(String args[]) {
        

        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    Login1 obj = new Login1();
                    new CurrentAccount(obj).setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(CurrentAccount.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton add;
    private javax.swing.JButton balance;
    private javax.swing.JButton benef;
    private javax.swing.JButton close;
    private javax.swing.JButton debit;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton request;
    // End of variables declaration                   
}


